services:
  - type: web
    name: data-analyzer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: auth_system
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
